baseurl = "https://maxmilton.com/"
languageCode = "en-uk"

title = "Max Milton"
theme = "mm"

uglyUrls = true
hasCJKLanguage = true
pluralizelisttitles = false
disableHugoGeneratorInject = true
rssuri = "rss.xml"
googleAnalytics = "UA-64694403-1"

[outputs]
home = ["html", "rss", "json"]
page = ["html", "json"]

[author]
  name = "Max Milton"
  email = "max@wearegenki.com"

[params]
  subtitle = "DevOps Engineer & Life Hacker."
  description = "The personal blog of Max Milton."
  themecolour = "#eceff1"

[[menu.main]]
  name = "All Posts"
  weight = 10
  url = "/blog.html"

[[menu.main]]
  name = "Quick Tips"
  weight = 20
  url = "/tags/quick-tips.html"
