# baseurl = "https://maxmilton.com/"
baseurl = "http://localhost:3000/" # FIXME: CHANGE WHEN PUBLISHING
languageCode = "en-uk"

title = "Max Milton"
theme = "mm"

uglyUrls = true
#canonifyurls = true
disableRSS = true

[params]
  subtitle = "Self-experimentation, Exploration, & Startups"
	description = "TODO: WRITE SITE DESCRIPTION."
	author = "Max Milton <max@wearegenki.com>"
  # TODO: Change themecolour depending on what the site main brand colour is
  themecolour = "#308ad8"
  googleAnalytics = "UA-64694403-1"

[[menu.main]]
  name = "All Posts"
  weight = -20
  url = "/blog"

[[menu.main]]
  name = "Quick Tips"
  weight = -10
  url = "/tags/quick-tips"
