baseurl = "https://maxmilton.com/"
languageCode = "en-uk"

title = "Max Milton"
theme = "mm"

uglyUrls = true
pluralizelisttitles = false
DisableHugoGeneratorInject = true
rssuri = "rss.xml"

hasCJKLanguage = true

copyright = "Blog posts are licensed under a Creative Commons Attribution No Derivatives 4.0 (CC-BY-ND-4.0) licence. When quoting my posts, please link back to the original article."

[author]
    name = "Max Milton"
    email = "max@wearegenki.com"

[params]
  subtitle = "Live life to the Max."
	description = "The personal blog of Max Milton."
  themecolour = "#eceeef"
  googleAnalytics = "UA-64694403-1"

[[menu.main]]
  name = "All Posts"
  weight = 10
  url = "/blog.html"

[[menu.main]]
  name = "Quick Tips"
  weight = 20
  url = "/tags/quick-tips.html"
