baseurl = "https://maxmilton.com/"
languageCode = "en-uk"

title = "Max Milton"
theme = "mm"

uglyUrls = true
#canonifyurls = true
disableRSS = true

[params]
  subtitle = "Self-experimentation, Exploration, Startups, & CX"
	description = "TODO: WRITE SITE DESCRIPTION."
	author = "Max Milton"
  # TODO: Change themecolour depending on what the site main brand colour is
  themecolour = "#308ad8"
