baseurl = "https://maxmilton.com/"
languageCode = "en-uk"

title = "Max Milton"
theme = "mm"

uglyUrls = true
# canonifyurls = true
# disableRSS = true
pluralizelisttitles = false

[params]
  subtitle = "Thinker. Adventurer. World Citizen."
	description = ""
	author = "Max Milton <max@wearegenki.com>"
  themecolour = "#eceeef"
  googleAnalytics = "UA-64694403-1"

[[menu.main]]
  name = "All Posts"
  weight = 10
  url = "/blog"

[[menu.main]]
  name = "Quick Tips"
  weight = 20
  url = "/tags/quick-tips"
