name = "MM"
license = "ISC"
licenselink = "https://github.com/MaxMilton/MaxMilton.com/blob/master/themes/mm/LICENSE.md"
description = "A simple theme designed for Max Milton's blog."
homepage = "https://github.com/MaxMilton/MaxMilton.com"
tags = ["misc", "quick tips", "linux"]
features = ["blog", "bootstrap v4", "nodjs build atuomation", "gulp"]
min_version = 0.14

[author]
  name = "Max Milton <max@wearegenki.com>"
  homepage = "https://MaxMilton.com"
